# Service registers under this name
# Control the InternalResourceViewResolver:

server:
  tomcat:
    max-connections: 10000
  port: 8082

logging:
  file:
    max-size: 10MB
    name: logs/application.log
  pattern:
    rolling-file-name: ../logs/application-%d{yyyy-MM-dd}-%i.log
spring:
    application:
      name: fis-resource-management
    datasourceFormManagement:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sphinx_db
      username: root
      password: 123456
    jpa:
      generate-ddl: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packagesToScan: com.fpt.fis.jira8api.controller
  pathsToMatch: /profiles/**


# Discovery Server Access


# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false

# HTTP (Tomcat) port
#server:
#  port: 2001
#  ip: localhost
#  url: http://localhost:2001
#  build: 1.0

mail:
  support: haivh12@fpt.com.vn

file:
  path: D:\file_load\
  image: D:\file_image\
#  avatar: F:\file_avatar_TGS\
  result_pdf : D:\file_result_pdf\
  result_docx : D:\file_result_docx\
